[package]
name = "domino-config-program"
version = "1.10.0"
description = "Domino Config program"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.131"
serde_derive = "1.0.103"
domino-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
domino-sdk = { path = "../../sdk", version = "=1.10.0" }

[dev-dependencies]
domino-logger = { path = "../../logger", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "domino_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
