[package]
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
edition = "2021"
name = "domino-net-shaper"
description = "The domino cluster network shaping tool"
version = "1.10.0"
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
publish = false

[dependencies]
clap = "2.33.1"
serde = "1.0.131"
serde_json = "1.0.73"
domino-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
rand = "0.7.0"

[[bin]]
name = "domino-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
