[package]
name = "domino-sdk-macro"
version = "1.10.0"
description = "Domino SDK Macro"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
