[package]
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
edition = "2021"
name = "domino-replica-lib"
description = "The library used for replication by both the client and server"
version = "1.10.0"
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-validator"

[dependencies]
crossbeam-channel = "0.5"
futures-util = "0.3"
log = "0.4.11"
prost = "0.9.0"
domino-rpc = { path = "../rpc", version = "=1.10.0" }
domino-runtime = { path = "../runtime", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.6.2", features = ["tls", "transport"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.6.2"
