[package]
name = "domino-bpf-loader-program"
version = "1.10.0"
description = "Domino BPF loader"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-bpf-loader-program"
edition = "2021"

[build-dependencies]
regex = "1.5.4"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
domino-measure = { path = "../../measure", version = "=1.10.0" }
domino-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
domino-sdk = { path = "../../sdk", version = "=1.10.0" }
domino_rbpf = "=0.2.19"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
domino-runtime = { path = "../../runtime", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "domino_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
