[package]
name = "domino-stake-program"
version = "1.10.0"
description = "Domino Stake program"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-stake-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.131"
serde_derive = "1.0.103"
domino-frozen-abi = { path = "../../frozen-abi", version = "=1.10.0" }
domino-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.10.0" }
domino-metrics = { path = "../../metrics", version = "=1.10.0" }
domino-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
domino-sdk = { path = "../../sdk", version = "=1.10.0" }
domino-vote-program = { path = "../vote", version = "=1.10.0" }
domino-config-program = { path = "../config", version = "=1.10.0" }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.0"
domino-logger = { path = "../../logger", version = "=1.10.0" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "domino_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
