[package]
name = "domino-runtime"
version = "1.10.0"
description = "Domino runtime"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-runtime"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.2.0"
bv = { version = "0.11.1", features = ["serde"] }
byteorder = "1.4.3"
bzip2 = "0.4.3"
dashmap = { version = "5.0.0", features = ["rayon", "raw-api"] }
crossbeam-channel = "0.5"
dir-diff = "0.3.2"
flate2 = "1.0.22"
fnv = "1.0.7"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
memmap2 = "0.5.0"
num_cpus = "1.13.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
ouroboros = "0.13.0"
rand = "0.8.4"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.131", features = ["rc"] }
serde_derive = "1.0.103"
domino-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.10.0" }
domino-config-program = { path = "../programs/config", version = "=1.10.0" }
domino-compute-budget-program = { path = "../programs/compute-budget", version = "=1.10.0" }
domino-frozen-abi = { path = "../frozen-abi", version = "=1.10.0" }
domino-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-measure = { path = "../measure", version = "=1.10.0" }
domino-metrics = { path = "../metrics", version = "=1.10.0" }
domino-bucket-map = { path = "../bucket_map", version = "=1.10.0" }
domino-program-runtime = { path = "../program-runtime", version = "=1.10.0" }
domino-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-stake-program = { path = "../programs/stake", version = "=1.10.0" }
domino-vote-program = { path = "../programs/vote", version = "=1.10.0" }
symlink = "0.1.0"
tar = "0.4.37"
tempfile = "3.2.0"
thiserror = "1.0"
zstd = "0.9.0"

[lib]
crate-type = ["lib"]
name = "domino_runtime"

[dev-dependencies]
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
assert_matches = "1.5.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
