[package]
name = "domino-transaction-status"
version = "1.10.0"
description = "Domino transaction status types"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-transaction-status"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
Inflector = "0.11.4"
lazy_static = "1.4.0"
log = "0.4.14"
serde = "1.0.131"
serde_derive = "1.0.103"
serde_json = "1.0.73"
domino-account-decoder = { path = "../account-decoder", version = "=1.10.0" }
domino-measure = { path = "../measure", version = "=1.10.0" }
domino-metrics = { path = "../metrics", version = "=1.10.0" }
domino-runtime = { path = "../runtime", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-vote-program = { path = "../programs/vote", version = "=1.10.0" }
spl-associated-token-account = { version = "=1.0.3", features = ["no-entrypoint"] }
spl-memo = { version = "=3.0.1", features = ["no-entrypoint"] }
spl-token = { version = "=3.2.0", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
