[package]
name = "domino-bpf-rust-128bit-dep"
version = "1.10.0"
description = "Domino BPF test program written in Rust"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-bpf-rust-128bit-dep"
edition = "2021"

[dependencies]
domino-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
