[package]
name = "domino-program-runtime"
version = "1.10.0"
description = "Domino program runtime"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
license = "Apache-2.0"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-program-runtime"
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
itertools =  "0.10.1"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = { version = "1.0.129", features = ["derive", "rc"] }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
thiserror = "1.0"

[lib]
crate-type = ["lib"]
name = "domino_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
