[package]
name = "rbpf-cli"
version = "1.10.0"
description = "CLI to test and analyze eBPF programs"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/rbpf"
homepage = "https://dominochain.com/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = "3.0.0-beta.2"
serde = "1.0.131"
serde_json = "1.0.73"
domino-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-program-runtime = { path = "../program-runtime", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
solana_rbpf = "=0.2.19"
time = "0.3.5"
