[package]
name = "domino-rayon-threadlimit"
version = "1.10.0"
description = "domino-rayon-threadlimit"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/domino-labs/domino"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
