[package]
name = "domino-cargo-test-bpf"
version = "1.10.0"
description = "Execute all unit and integration tests after building with the Domino BPF SDK"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
homepage = "https://dominochain.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.14.1"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
