[package]
name = "domino-frozen-abi-macro"
version = "1.10.0"
description = "Domino Frozen ABI Macro"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/domino-labs/domino"
homepage = "https://domino.com/"
documentation = "https://docs.rs/domino-frozen-abi-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[build-dependencies]
rustc_version = "0.4"
