[package]
name = "domino-rpc-test"
version = "1.10.0"
description = "Domino RPC Test"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-rpc-test"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
log = "0.4.11"
reqwest = { version = "0.11.5", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.131"
serde_json = "1.0.73"
domino-account-decoder = { path = "../account-decoder", version = "=1.10.0" }
domino-client = { path = "../client", version = "=1.10.0" }
domino-rpc = { path = "../rpc", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-streamer = { path = "../streamer", version = "=1.10.0" }
domino-test-validator = { path = "../test-validator", version = "=1.10.0" }
domino-transaction-status = { path = "../transaction-status", version = "=1.10.0" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
domino-logger = { path = "../logger", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
