[package]
name = "domino-measure"
description = "Blockchain, Rebuilt for Scale"
version = "1.10.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-measure"
readme = "../README.md"
repository = "https://github.com/Domino-Blockchain/domino"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"
domino-sdk = { path = "../sdk", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
